### ISSUE TITLE
`vue-tsc --noEmit` fails

### ISSUE THREAD

**Issue by WhyNotHugo** [jaw52/unplugin-svg-vue-component#1]
```con
> yarn vue-tsc --noEmit
yarn run v1.22.19
$ '/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/.bin/vue-tsc' --noEmit
/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/@volar/vue-language-core/out/sourceFile.js:348
            updateTemplate(parsedSfc.value.descriptor.template);
                                                      ^

TypeError: Cannot read properties of undefined (reading 'template')
    at update (/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/@volar/vue-language-core/out/sourceFile.js:348:55)
    at createSourceFile (/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/@volar/vue-language-core/out/sourceFile.js:314:5)
    at update (/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/@volar/vue-language-core/out/lsContext.js:243:82)
    at Object.get (/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/@volar/vue-language-core/out/lsContext.js:158:17)
    at Object.createLanguageService (/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/typescript/lib/tsserverlibrary.js:169183:94)
    at Object.createLanguageService (/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/@volar/vue-typescript/out/index.js:9:19)
    at Object.createProgramProxy (/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/vue-tsc/out/proxy.js:48:31)
    at Object.createProgram (/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/typescript/lib/tsc.js:98760:211)
    at performCompilation (/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/typescript/lib/tsc.js:107870:26)
    at executeCommandLineWorker (/home/hugo/src/git.sr.ht/~whynothugo/photostore/node_modules/typescript/lib/tsc.js:107744:17)

Node.js v18.17.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My `tsconfig` includes the `types` mentioned in the readme:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": ["vite/client", "google.maps", "unplugin-svg-vue-component/client"],
    "skipLibCheck": true,
    "paths": {
      "@/*": ["src/*"]
    },
    "lib": ["esnext", "dom", "dom.iterable", "scripthost"]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": ["node_modules"],
    "vueCompilerOptions": {
    "experimentalCompatMode": 2,
    "experimentalTemplateCompilerOptions": {
      "compatConfig": { "MODE": 2 }
    }
  }
}
```

I'm using Vue 2.7.

**Comment by WhyNotHugo** [comment]
Upgrading `vue-tsc` fixed it:

```diff
-    "vue-tsc": "^0.40.0",
+    "vue-tsc": "^1.8.11",
```
